### ISSUE TITLE
User Guide: TreeTagger instructions refer to .jy file

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/DARIAH-DKPro-Wrapper#13]
The [installation instructions for TreeTagger in the user guide](https://github.com/DARIAH-DE/DARIAH-DKPro-Wrapper/blob/master/doc/user-guide.adoc#treetagger-installation-for-linux) mention treetagger.jy in both the windows and linux instructions, this is no longer up-to-date.

**Comment by severinsimmler** [comment]
Updated in user-guide.adoc as well as in tutorial.adoc
