### ISSUE TITLE
index: Download folder as ZIP not possible

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/DARIAH-DKPro-Wrapper#19]
As mentioned in [index.adoc](https://github.com/DARIAH-DE/DARIAH-DKPro-Wrapper/blob/master/doc/index.adoc), downloading the folder **Configuration files** as a ZIP archive is not possible. `link:configs.zip` leads to 404 Not Found. See also: [this](http://stackoverflow.com/questions/23436711/generate-download-link-for-a-single-folder-in-github). Any other solutions?

**Comment by thvitt** [comment]
Yes, the maven build can just generate this, only the job needs to be configured & the stuff included in release, though
